# Generated by Django 5.1.5 on 2025-01-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('categoria', models.CharField(max_length=50)),
                ('tags', models.JSONField(default=True)),
                ('criadoEm', models.DateTimeField(auto_now_add=True)),
                ('editadoEm', models.DateField(auto_now=True)),
            ],
        ),
    ]
