# Generated by Django 5.1.5 on 2025-01-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0002_alter_artigos_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artigos',
            new_name='Artigo',
        ),
    ]
